import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import ClipLoader from "react-spinners/ClipLoader";
import { FaDownload } from "react-icons/fa";
import axiosSecure from "../../../../api/axiosSecure";

const Merchant_Invoices_Admin = () => {

  // ================= PAGINATION =================

  const [currentPage, setCurrentPage] =
    useState(1);

  const itemsPerPage = 30;

  // ================= FETCH INVOICES =================

  const {
    data: InvoiceData = [],
    isLoading,
  } = useQuery({

    queryKey: ["InvoiceDataAdmin"],

    queryFn: async () => {

      const res =
        await axiosSecure.get(
          "/invoice"
        );

      return res.data || [];
    },
  });

  // ================= DATE FORMAT =================

  const formatDate = (date) => {

    return new Date(
      date
    ).toLocaleString();
  };

  // ================= PAGINATION LOGIC =================

  const totalPages = Math.ceil(
    InvoiceData.length / itemsPerPage
  );

  const startIndex =
    (currentPage - 1) * itemsPerPage;

  const endIndex =
    startIndex + itemsPerPage;

  const paginatedInvoices =
    InvoiceData.slice(
      startIndex,
      endIndex
    );

  // ================= LOADING =================

  if (isLoading) {

    return (
      <div className="flex justify-center items-center h-[300px]">

        <ClipLoader
          color="#2563eb"
          size={50}
        />

      </div>
    );
  }

  return (
    <div className="p-6">

      {/* HEADER */}

      <div className="mb-6">

        <h1 className="text-3xl font-bold text-gray-800">

          Merchant Invoices

        </h1>

        <p className="text-gray-500 mt-1">

          View and download all generated invoices

        </p>
      </div>

      {/* EMPTY */}

      {InvoiceData.length === 0 && (

        <div className="bg-white shadow rounded-xl p-10 text-center">

          <h2 className="text-xl font-semibold text-gray-700">

            No Invoice Found

          </h2>

          <p className="text-gray-500 mt-2">

            No invoices available.

          </p>

        </div>
      )}

      {/* TABLE */}

      {InvoiceData.length > 0 && (

        <>
          <div className="overflow-x-auto bg-white rounded-xl shadow">

            <table className="table w-full">

              <thead className="bg-blue-600 text-white">

                <tr>

                  <th>SL</th>

                  <th>Merchant Name</th>

                  <th>Merchant ID</th>

                  <th>Merchant Email</th>

                  <th>Created At</th>

                  <th>Generated By</th>

                  <th>Download</th>

                </tr>
              </thead>

              <tbody>

                {paginatedInvoices.map(
                  (invoice, index) => (

                    <tr
                      key={invoice._id}
                      className="hover"
                    >

                      <td>
                        {startIndex + index + 1}
                      </td>

                      <td>
                        {invoice?.merchantName ||
                          "N/A"}
                      </td>

                      <td>
                        {invoice?.merchantID ||
                          "N/A"}
                      </td>

                      <td>
                        {invoice?.merchantEmail ||
                          "N/A"}
                      </td>

                      <td>
                        {formatDate(
                          invoice?.createdAt
                        )}
                      </td>

                      <td>

                        <div>

                          <p className="font-medium">
                            {
                              invoice?.Who_Added
                            }
                          </p>

                          <p className="text-sm text-gray-500">
                            {
                              invoice?.Who_Added_Email
                            }
                          </p>

                        </div>

                      </td>

                      <td>

                        <a
                          href={
                            invoice?.pdfUrl
                          }

                          target="_blank"

                          rel="noopener noreferrer"

                          className="inline-flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition"
                        >

                          <FaDownload />

                          Download

                        </a>

                      </td>

                    </tr>
                  )
                )}
              </tbody>
            </table>
          </div>

          {/* PAGINATION */}

          <div className="flex justify-center mt-6 gap-2 flex-wrap">

            <button
              onClick={() =>
                setCurrentPage(
                  currentPage - 1
                )
              }

              disabled={
                currentPage === 1
              }

              className="px-4 py-2 rounded bg-gray-200 disabled:opacity-50"
            >
              Prev
            </button>

            {[
              ...Array(totalPages).keys(),
            ].map((page) => (

              <button
                key={page + 1}

                onClick={() =>
                  setCurrentPage(
                    page + 1
                  )
                }

                className={`px-4 py-2 rounded ${
                  currentPage ===
                  page + 1
                    ? "bg-blue-600 text-white"
                    : "bg-gray-200"
                }`}
              >
                {page + 1}
              </button>
            ))}

            <button
              onClick={() =>
                setCurrentPage(
                  currentPage + 1
                )
              }

              disabled={
                currentPage === totalPages
              }

              className="px-4 py-2 rounded bg-gray-200 disabled:opacity-50"
            >
              Next
            </button>
          </div>
        </>
      )}
    </div>
  );
};

export default Merchant_Invoices_Admin;