import { useQuery } from "@tanstack/react-query";
import ClipLoader from "react-spinners/ClipLoader";
import axiosSecure from "../../../../api/axiosSecure";
import useUsersData from "../../../../hooks/useUsersData/useUsersData";
import { FaDownload } from "react-icons/fa";

const MerchantInvoices = () => {

  const [verifiedUser] =
    useUsersData();

  // ================= FETCH DATA =================

  const {
    data: InvoiceData = [],
    isLoading,
  } = useQuery({

    queryKey: [
      "InvoiceData",
      verifiedUser?.email,
    ],

    queryFn: async () => {

      const res =
        await axiosSecure.get(
          "/invoice"
        );

      return res.data;
    },

    enabled:
      !!verifiedUser?.email,
  });

  // ================= FILTER =================

  const filteredInvoices =
    InvoiceData.filter(
      (invoice) =>
        invoice.merchantEmail ===
        verifiedUser?.email
    );

  // ================= DATE FORMAT =================

  const formatDate = (date) => {

    return new Date(
      date
    ).toLocaleString();
  };

  // ================= LOADING =================

  if (isLoading) {

    return (
      <div className="flex justify-center items-center h-[300px]">

        <ClipLoader
          color="#2563eb"
          size={50}
        />

      </div>
    );
  }

  return (
    <div className="p-6">

      {/* HEADER */}

      <div className="mb-6">

        <h1 className="text-3xl font-bold text-gray-800">

          Merchant Invoices

        </h1>

        <p className="text-gray-500 mt-1">

          View and download your generated invoices

        </p>
      </div>

      {/* EMPTY */}

      {filteredInvoices.length === 0 && (

        <div className="bg-white shadow rounded-xl p-10 text-center">

          <h2 className="text-xl font-semibold text-gray-700">

            No Invoice Found

          </h2>

          <p className="text-gray-500 mt-2">

            No invoices available for your account.

          </p>

        </div>
      )}

      {/* TABLE */}

      {filteredInvoices.length > 0 && (

        <div className="overflow-x-auto bg-white rounded-xl shadow">

          <table className="table w-full">

            <thead className="bg-blue-600 text-white">

              <tr>

                <th>SL</th>

                <th>Merchant Name</th>

                <th>Merchant ID</th>

                <th>Created At</th>

                <th>Generated By</th>

                <th>Download</th>

              </tr>
            </thead>

            <tbody>

              {filteredInvoices.map(
                (invoice, index) => (

                  <tr
                    key={invoice._id}
                    className="hover"
                  >

                    <td>
                      {index + 1}
                    </td>

                    <td>
                      {invoice?.merchantName ||
                        "N/A"}
                    </td>

                    <td>
                      {invoice?.merchantID ||
                        "N/A"}
                    </td>

                    <td>
                      {formatDate(
                        invoice?.createdAt
                      )}
                    </td>

                    <td>

                      <div>

                        <p className="font-medium">
                          {
                            invoice?.Who_Added
                          }
                        </p>

                      

                      </div>

                    </td>

                    <td>

                      <a
                        href={
                          invoice?.pdfUrl
                        }

                        target="_blank"

                        rel="noopener noreferrer"

                        className="inline-flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition"
                      >

                        <FaDownload />

                        Download

                      </a>

                    </td>

                  </tr>
                )
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default MerchantInvoices;